package:
  name: vtk
  version: "7.0.0"

source:
  fn: VTK-7.0.0.tar.gz
  url: http://www.vtk.org/files/release/7.0/VTK-7.0.0.tar.gz
  sha1: 7719fac36b36965eaf5076542166ba49bbe7afbb

build:
  number: 0

requirements:
  build:
   - python
   - cmake
   - hdf5

  run:
   - python
   - hdf5

test:
  requires:
    - numpy
    - pillow

  imports:
    - vtk

about:
  home: http://www.vtk.org
  license: BSD
